name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace 'x' with the desired Python version

      - name: Install dependencies
        run: pip install pyinstaller colorama

      - name: Build executable
        run: pyinstaller --onefile wowparser.py

      - name: Zip executable
        run: 7z a wowparser.zip dist\wowparser.exe

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Main
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wowparser.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "Executable build for the parser. Make sure it's released by github-actions before downloading."
